/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Control_Reg_1.h"
#include "Control_Reg_2.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "Pin_7_aliases.h"
#include "Pin_7.h"
#include "Pin_8_aliases.h"
#include "Pin_8.h"
#include "Pin_9_aliases.h"
#include "Pin_9.h"
#include "Pin_10_aliases.h"
#include "Pin_10.h"
#include "Pin_11_aliases.h"
#include "Pin_11.h"
#include "Pin_12_aliases.h"
#include "Pin_12.h"
#include "Pin_15_aliases.h"
#include "Pin_15.h"
#include "Comp_1.h"
#include "VDAC8_1.h"
#include "Pin_16_aliases.h"
#include "Pin_16.h"
#include "Pin_25_aliases.h"
#include "Pin_25.h"
#include "UART_1.h"
#include "Pin_22_aliases.h"
#include "Pin_22.h"
#include "Pin_23_aliases.h"
#include "Pin_23.h"
#include "isr_2.h"
#include "isr_3.h"
#include "Clock_2.h"
#include "beeperpin_aliases.h"
#include "beeperpin.h"
#include "Pin_24_aliases.h"
#include "Pin_24.h"
#include "EEPROM_1.h"
#include "isr_5.h"
#include "isr_4.h"
#include "Clock_1.h"
#include "Clock_3.h"
#include "counter_reset.h"
#include "isr_1.h"
#include "Pin_13_aliases.h"
#include "Pin_13.h"
#include "Opamp_1.h"
#include "PGA_1.h"
#include "Timer_1.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

